[project]
authors = ["Ilya Orson Sandoval <ilya.orson@gmail.com>"]
channels = ["pytorch", "conda-forge"]
description = "Fast Gradient Sign Method in PyTorch"
name = "FGSM"
platforms = ["win-64","linux-64","osx-arm64","osx-64"]
version = "0.1.0"

[host-dependencies]
python = "~=3.11"

[dependencies]
# Common dependencies for both environments
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
ipython = ">=8.30.0,<9"
ruff = ">=0.8.1,<0.9"

[feature.cpu.dependencies]
# CPU-only dependencies
cpuonly = "*"

[feature.cuda]
# CUDA-specific requirements
platforms = ["linux-64", "win-64"]
system-requirements = {cuda = "11.8"}
channels = ["nvidia", {channel = "pytorch", priority = -1}]
[feature.cuda.dependencies]
pytorch-cuda = "11.8.*"

[environments]
# All environments include the "default" feature
cpu = ["cpu"]
cuda = ["cuda"]  # This is read as ["default", "cuda"]

[tasks]
test-cuda = "python test_cuda.py"
format = "ruff format"